name: telesa_english_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  just_audio_background: ^0.0.1-beta.17
  get_it: ^8.0.3
  injectable: ^2.5.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.30
  lottie: ^3.3.1
  dio: ^5.8.0+1
  firebase_database: ^12.0.0
  widgetbook: ^3.14.3
  google_fonts: ^6.2.1
  flutter_localization: ^0.3.3
  #  intl: 0.20.2
  flutter_animate: ^4.5.2
  google_sign_in: ^7.1.1
  flutter_dotenv: ^5.2.1
  overlay_notification: ^23.5.12
  go_router: ^16.1.0
  loader_overlay: ^5.0.0
  event_bus: ^2.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.9.0
  freezed: ^3.1.0
  #  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/core/constants/generated/
  # line_length: 80 # Optional

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    enabled: true # Optional
    outputs: # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: camel-case # Optional
      class_name: AppAssets
    exclude: [ ]

flutter_intl:
  enabled: true
  arb_dir: lib/core/translations
  output_dir: lib/core/translations/generated
  class_name: AppTranslate
  main_locale: en

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/png/
    - .env
